name: Build and Test

on:
  push:
    branches: ["**"] # Runs on all branches
  pull_request:
    branches: ["**"] # Runs on PRs targeting any branch
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  pull-requests: read

env:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
          cache-dependency-path: "pom.xml"

      - name: Build and test with Maven
        run: mvn -B clean verify

      # - name: Upload test results
      #   if: always()  # Always run this step even if previous steps fail
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-results
      #     path: '**/target/surefire-reports/**/*.xml'
      #     if-no-files-found: ignore
